obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.1, -0.1], [-0.5, 0.5], [0.3, 0.3], [0.1, 0.0], [0.1, -0.1]]
footprint_padding: 0.05
inflation_radius: 0.60

observation_sources: hokuyo_laser
hokuyo_laser: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /ales/laser/scan, marking: true, clearing: true}
