obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.35, -0.35], [-0.35, 0.35], [0.65, 0.35], [0.65, -0.35]]
footprint_padding: 0.05
inflation_radius: 0.77

observation_sources: hokuyo_laser
hokuyo_laser: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /ales/laser/scan, marking: true, clearing: true}
