global_costmap:

  map_type: costmap
  track_unknown_space: true
  unknown_cost_value: 255
  obstacle_range: 2.5
  raytrace_range: 3.0
  footprint: [[-0.35, -0.35], [-0.35, 0.35], [0.65, 0.35], [0.65, -0.35]]
  inflation_radius: 0.77
  transform_tolerance: 0.5
  inscribed_radius: 0.77
  # circumscribed_radius: 0.70

  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 5
  publish_frequency: 5
  static_map: true
  rolling_window: false

  #Investigate what this actually does
  cost_scaling_factor: 10.0
